In [1]:
import numpy as np

### a) - f)

In [ ]:
# a) Null vector of size 10, 5th value equals one
a  = np.zeros(10)
a [4] = 1
print(f" a): {a} \n")

# b) Create a vector with values ranging from 10 to 49
b = np.arange(10,50)
print(f" b): {b} \n")


#c. Reverse a vector (first element becomes last)
c = b[::-1]
print(f" c): {c} \n")


#d. Create a 3x3 matrix with values ranging from 0 to 8
d = np.arange(0,9).reshape(3,3)
print(f" d): \n {d} \n")


#e. Find indices of non-zero elements from [1,2,0,0,4,0]
e = np.array([1,2,0,0,4,0])
e_nonzero_indices = np.nonzero(e)
print(f" e): \n {e_nonzero_indices} \n")

#f. Create a random vector of size 30 and find the mean value
f = np.random.rand(30)
f_mean = np.mean(f)
print(f" f): mean = {f_mean}, f = \n {f} \n")



 a): [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] 

 b): [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

 c): [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10] 

 d): 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

 e): 
 (array([0, 1, 4]),) 

 f): mean = 0.35769862860769946, f = 
 [0.03782614 0.63118476 0.61792826 0.84870185 0.38560193 0.5545476
 0.03645976 0.32812482 0.88499374 0.36085331 0.2260952  0.89367429
 0.25506015 0.03398513 0.02239822 0.34750043 0.09967243 0.19873871
 0.60091579 0.60794533 0.26458041 0.65220873 0.45829906 0.35333916
 0.08591854 0.36691942 0.06771968 0.00829334 0.22877849 0.27269419] 

 g): g_naive: 
 [[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]] 
 g_pad: 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]] 



### g) - i)

In [ ]:
#g. Create a 2d array with 1 on the border and 0 inside
N1 = 5
N2 = 10

# Naive way
g = np.zeros((N1,N2))
g[:,0] = 1
g[0,:] = 1
g[:,N2-1] = 1
g[N1-1,:] = 1

# Using padding function from https://www.geeksforgeeks.org/python/how-to-add-a-border-around-a-numpy-array/
# Although this ADDS a border around it instead of just replacing the one above
# Subtract two from both sides since pad adds that many elements in each axis
g_pad = np.pad(np.zeros((N1-2,N2-2)), pad_width=1, mode="constant", constant_values=1)
print(f" g): g_naive: \n {g} \n g_pad: \n {g_pad} \n\n")


# h. Create a 8x8 matrix and fill it with a checkerboard pattern
dim = 8
h = np.indices((dim,dim)).sum(axis=0) % 2
#dim = 9
#h = np.resize([1, 0], dim**2).reshape(dim, dim) # only fworks for odd dimensions
print(f" h): \n {h} \n")

#i. Create a checkerboard 8x8 matrix using the tile function
tile = np.array([[1, 0],[0, 1]]) # only works for even dimensions
i = np.tile(tile, (dim//2, dim//2))
print(f" i): \n {i} \n")

 g): g_naive: 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] 
 g_pad: 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] 


 h): 
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]] 

 j): 
 [[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]] 



### i)

In [ ]:
#j. Given a 1D array, negate all elements which are between 3 and 8, in place
j = np.arange(11)
# Only values between 3 and 8, 3 and 8 not included (if i understood correctly)
j[4:8] *= -1
print(f" j): \n {j} \n")


#k. Create a random vector of size 10 and sort it
import random
size=10
k = np.arange(0, size)
np.random.shuffle(k)
print(f" k): unsorted: {k}")
#using my favorite sorting algorithm bogosort. Dont go over 10 please
# Fastest algorithm (if you're lucky)
while not np.array_equal(k, np.arange(0, size)):
    np.random.shuffle(k)
print(f"  sorted! {k} \n")



 j): 
 [ 0  1  2  3 -4 -5 -6 -7  8  9 10] 

 k): unsorted: [4 1 5 6 0 2 8 9 7 3]
  sorted! [0 1 2 3 4 5 6 7 8 9] 



In [215]:
#l. Consider two random array A anb B, check if they are equal
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.array_equal(A, B)
print(f" l): Arrays equal? {equal}")


#m. How to calculate the square of every number in an array in place (without creating temporaries)?
m = np.arange(10, dtype=np.int32)
print(m)
#m[:] = m**2 # modifies the original array since [:] points to the memory buffer containing the data
m *= m # simplest solution
print(f"m) Squared array: {m}")

 l): Arrays equal? False
[0 1 2 3 4 5 6 7 8 9]
m) Squared array: [ 0  1  4  9 16 25 36 49 64 81]


In [ ]:
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D = np.array([C[i,i] for i in range(C.shape[0])])
print(D)

[ 18  66 132]
